config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  get '/sign-in' => 'sessions#new'
  delete '/sign-out' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  resources :wolves

  resources :recyclers

  root 'static#home'

  get '/about' => 'static#about'

  get '/cat-pictures'                 => 'static#cats'
  get '/cat-pictures(/:number_of_cats)' => 'static#cats'

end

app/models/recycler.rb
class Recycler < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :email
end

app/models/wolf.rb
class Wolf < ActiveRecord::Base
  validates_presence_of :name, :species, :pack_rank
  validates_presence_of :pack_number, :message =>"required if not loner", :if => :not_loner?
  validates :pack_number, :numericality => { :greater_than_or_equal_to => 0 }, :if => :not_loner?

  def not_loner?
    pack_rank != 'Loner'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
private

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def user_signed_in?
    !!current_user
  end
  helper_method :user_signed_in?

  def only_allow_signed_in_users
    unless user_signed_in?
      redirect_to sign_in_url, notice: 'You must sign in to access this part of the app.'
    end
  end
end

app/controllers/recyclers_controller.rb
class RecyclersController < ApplicationController
  before_action :set_recycler, only: [:show, :edit, :update, :destroy]

  # GET /recyclers
  # GET /recyclers.json
  def index
    @recyclers = Recycler.all
  end

  # GET /recyclers/1
  # GET /recyclers/1.json
  def show
  end

  # GET /recyclers/new
  def new
    @recycler = Recycler.new
  end

  # GET /recyclers/1/edit
  def edit
  end

  # POST /recyclers
  # POST /recyclers.json
  def create
    @recycler = Recycler.new(recycler_params)

    respond_to do |format|
      if @recycler.save
        format.html { redirect_to @recycler, notice: 'Recycler was successfully created.' }
        format.json { render :show, status: :created, location: @recycler }
      else
        format.html { render :new }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recyclers/1
  # PATCH/PUT /recyclers/1.json
  def update
    respond_to do |format|
      if @recycler.update(recycler_params)
        format.html { redirect_to @recycler, notice: 'Recycler was successfully updated.' }
        format.json { render :show, status: :ok, location: @recycler }
      else
        format.html { render :edit }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recyclers/1
  # DELETE /recyclers/1.json
  def destroy
    @recycler.destroy
    respond_to do |format|
      format.html { redirect_to recyclers_url, notice: 'Recycler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recycler
      @recycler = Recycler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recycler_params
      params.require(:recycler).permit(:name, :address, :phone, :website, :email, :accepts_white_computer_paper, :accepts_corrugated_cardboard, :accepts_color_separated_glass)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: user_params[:email])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.alert = 'Invalid email/password combination. Please try again.'
      @user = User.new
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Successfully signed out!'
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def cats
    @cats = CatAPI.new.get_images(results_per_page: params[:number_of_cats] || 1)
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb

class UsersController < ApplicationController

    def new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to '/'
      else
        render 'sessions/new'
      end
    end

private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/wolves_controller.rb
class WolvesController < ApplicationController
  before_action :only_allow_signed_in_users, except: [:index, :show]
  before_action :set_wolf, only: [:show, :edit, :update, :destroy]

  # GET /wolves
  # GET /wolves.json
  def index
    @wolves = Wolf.all
  end

  # GET /wolves/1
  # GET /wolves/1.json
  def show
  end

  # GET /wolves/new
  def new
    @wolf = Wolf.new
  end

  # GET /wolves/1/edit
  def edit
  end

  # POST /wolves
  # POST /wolves.json
  def create
    @wolf = Wolf.new(wolf_params)

    respond_to do |format|
      if @wolf.save
        format.html { redirect_to @wolf, notice: 'Wolf was successfully created.' }
        format.json { render :show, status: :created, location: @wolf }
      else
        format.html { render :new }
        format.json { render json: @wolf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wolves/1
  # PATCH/PUT /wolves/1.json
  def update
    respond_to do |format|
      if @wolf.update(wolf_params)
        format.html { redirect_to @wolf, notice: 'Wolf was successfully updated.' }
        format.json { render :show, status: :ok, location: @wolf }
      else
        format.html { render :edit }
        format.json { render json: @wolf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wolves/1
  # DELETE /wolves/1.json
  def destroy
    @wolf.destroy
    respond_to do |format|
      format.html { redirect_to wolves_url, notice: 'Wolf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wolf
      @wolf = Wolf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wolf_params
      params.require(:wolf).permit(:name, :species, :pack_rank, :pack_number, :is_alive)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recyclers_helper.rb
module RecyclersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
  def current_date_and_time
    Time.now.strftime('%B %-d, %Y at %-l:%M%P')
  end
end

app/helpers/wolves_helper.rb
module WolvesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TC359 Final Project</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Wolves Directory', wolves_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Signed in as " + current_user.email %></li>
            <li><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", sign_in_path %></li>
          <% end %>
        </ul>
      </div>
  	</div>
  </nav>

  <div class="container">
    <div class="panel panel-default">
      <div class="panel-body">
        <% flash.each do |type, message| %>
          <div class="<%= type %>">
            <p><%= message %></p>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/recyclers/_form.html.erb
<%= form_for(@recycler) do |f| %>
  <% if @recycler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recycler.errors.count, "error") %> prohibited this recycler from being saved:</h2>

      <ul>
      <% @recycler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :accepts_white_computer_paper %><br>
    <%= f.check_box :accepts_white_computer_paper %>
  </div>
  <div class="field">
    <%= f.label :accepts_corrugated_cardboard %><br>
    <%= f.check_box :accepts_corrugated_cardboard %>
  </div>
  <div class="field">
    <%= f.label :accepts_color_separated_glass %><br>
    <%= f.check_box :accepts_color_separated_glass %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recyclers/edit.html.erb
<h1>Editing Recycler</h1>

<%= render 'form' %>

<%= link_to 'Show', @recycler %> |
<%= link_to 'Back', recyclers_path %>

app/views/recyclers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recyclers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Email</th>
      <th>Accepts white computer paper</th>
      <th>Accepts corrugated cardboard</th>
      <th>Accepts color separated glass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recyclers.each do |recycler| %>
      <tr>
        <td><%= recycler.name %></td>
        <td><%= recycler.address %></td>
        <td><%= recycler.phone %></td>
        <td><%= recycler.website %></td>
        <td><%= recycler.email %></td>
        <td><%= recycler.accepts_white_computer_paper %></td>
        <td><%= recycler.accepts_corrugated_cardboard %></td>
        <td><%= recycler.accepts_color_separated_glass %></td>
        <td><%= link_to 'Show', recycler %></td>
        <td><%= link_to 'Edit', edit_recycler_path(recycler) %></td>
        <td><%= link_to 'Destroy', recycler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recycler', new_recycler_path %>

app/views/recyclers/new.html.erb
<h1>New Recycler</h1>

<%= render 'form' %>

<%= link_to 'Back', recyclers_path %>

app/views/recyclers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recycler.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @recycler.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @recycler.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @recycler.website %>
</p>

<p>
  <strong>Email:</strong>
  <%= @recycler.email %>
</p>

<p>
  <strong>Accepts white computer paper:</strong>
  <%= @recycler.accepts_white_computer_paper %>
</p>

<p>
  <strong>Accepts corrugated cardboard:</strong>
  <%= @recycler.accepts_corrugated_cardboard %>
</p>

<p>
  <strong>Accepts color separated glass:</strong>
  <%= @recycler.accepts_color_separated_glass %>
</p>

<%= link_to 'Edit', edit_recycler_path(@recycler) %> |
<%= link_to 'Back', recyclers_path %>

app/views/wolves/_form.html.erb
<%= simple_form_for @wolf do |f| %>
  <%= f.input :name %>
  <%= f.input :species %>
  <%= f.input :pack_rank %>
  <%= f.input :pack_number %>
  <%= f.input :is_alive %>
  <%= f.button :submit, id: "button_to" %>
<% end %>

app/views/wolves/edit.html.erb
<h1>Editing Wolf</h1>

<%= render 'form' %>

<%= link_to 'Show', @wolf %> |
<%= link_to 'Back', wolves_path %>

app/views/wolves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wolves</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Species</th>
      <th>Pack rank</th>
      <th>Pack number</th>
      <th>Is alive?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wolves.each do |wolf| %>
      <tr>
        <td><%= wolf.name %></td>
        <td><%= wolf.species %></td>
        <td><%= wolf.pack_rank %></td>
        <td><%= wolf.pack_number %></td>
        <td><%= wolf.is_alive %></td>
        <td><%= link_to 'Show', wolf %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_wolf_path(wolf) %></td>
        <td><%= link_to 'Destroy', wolf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New Wolf', new_wolf_path %>
<% end %>

app/views/wolves/new.html.erb
<h1>New Wolf</h1>

<%= render 'form' %>
<%= button_to 'Back', wolves_path, class: "btn btn-default", id: "back_button" %>

app/views/wolves/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Wolf: <%= @wolf.name %></h1>
<hr>
<p>
  <strong>Name:</strong>
  <%= @wolf.name %>
</p>

<p>
  <strong>Species:</strong>
  <%= @wolf.species %>
</p>

<p>
  <strong>Pack rank:</strong>
  <%= @wolf.pack_rank %>
</p>

<p>
  <strong>Pack number:</strong>
  <%= @wolf.pack_number %>
</p>

<p>
  <strong>Is alive:</strong>
  <%= @wolf.is_alive %>
</p>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_wolf_path(@wolf) %> |
<% end %>
<%= link_to 'Back', wolves_path %>